#! /usr/bin/python
import fishmake
from   pybase.config import GlobalConfig as PyConfig

PyConfig.init(".fishmake", fishmake.Defaults)

def main():
	fishmake.configure()
	if   PyConfig[0] == "clean":
		return fishmake.clean()
	elif PyConfig[0] == "compile":
		return fishmake.compile()
	elif PyConfig[0] == "install":
		return fishmake.install()
	elif PyConfig[0] == "doc":
		return fishmake.doc()
	else:
		print "Usage: fishmake <clean|compile|install>"
		return 0

main()